### ISSUE TITLE
[Feature] :  As a user I would like to remove products from the cart, so that if I change my mind about a product I can remove it

### ISSUE THREAD

**Issue by emaranald22** [Patkeenz/SOEN341_Team3#21]

**Comment by melisa1026** [comment]
1. Make sure to be logged in
2. Select the item you are interested in
3. Click on add item to cart
4. Click the cart icon
5. Verify the item was added to the cart

**Comment by melisa1026** [comment]
1. Go to your cart
2. On the item you would like the change, click delete
