### ISSUE TITLE
[Feature] : As a user I would like to add a payment method, to be able to purchase an item from the website

### ISSUE THREAD

**Issue by emaranald22** [Patkeenz/SOEN341_Team3#33]

**Comment by emaranald22** [comment]
**Tasks**
- Create the form (Melisa)
- Saving the information (Melisa)
- Create the style (Eman)

**Comment by melisa1026** [comment]
1. Click the cart icon
2. Click checkout
3. Click choose a payment method
4. Fill out your credit card and shipping information
5. Click Submit
6. Make sure an order confirmation appears
