### ISSUE TITLE
[User Feature]: As a user I would like to be able to place an order, to get the product I am interested in

### ISSUE THREAD

**Issue by emaranald22** [Patkeenz/SOEN341_Team3#35]

**Comment by emaranald22** [comment]
**Tasks**
- Create order fields in the database that needs to be recorded
- Create button to place order

**Comment by melisa1026** [comment]
1. Click the cart icon
2. Click checkout
3. Click choose a payment method
4. Fill out your credit card and shipping information
5. Click Submit
6. Make sure an order confirmation appears
