### ISSUE TITLE
[FEATURE]: Adding products to the cart

### ISSUE THREAD

**Issue by Shiv2205** [Patkeenz/SOEN341_Team3#4]
## User Story: 
As an online shopper, I want to be able to add any product to my cart easily and instantly.

## Estimation of effort
TBD

## Acceptance Criteria
TBD

**Comment by emaranald22** [comment]
1) Make sure to be logged in
2) Select the item you are interested in
3) Click on add item to cart
4) Click the cart icon 
5) Verify the item was added to the cart
