### ISSUE TITLE
[FEATURE]: Browsing Items

### ISSUE THREAD

**Issue by melisa1026** [Patkeenz/SOEN341_Team3#5]
## User Story
As an online shopper, I would like to browse through suggested products and search for specific ones.

## Estimation Effort
TBD

## Acceptance Criteria
TBD

**Comment by George-Hdd** [comment]
All tasks for Epic 1 are done and tested. Milestones for Sprint 2 met on time.

**Comment by emaranald22** [comment]
1) Make sure to be logged in.
2) Go to the home page
3) All the items should be available to browse
4) Select a category at the top
5) Click search
7) Ensure the only items are available were those in the category selected
